- themes/cuivory/css/ivory-styles.css
- themes/cuivory/scss/ivory-styles.scss
- themes/cushadow/css/shadow-styles.css
- themes/cushadow/scss/shadow-styles.scss
To test:
1. Create some basic page content
2. Switch theme to Ivory and Shadow
3. View pages at different browser widths
> Horizontal padding issue on Ivory and Shadow themes Bug/151

- modules/custom/cu_section_page_bundle/css/cu-section-page.css
- modules/custom/cu_section_page_bundle/scss/cu-section-page.scss
- modules/features/cu_block_section/css/cu-block-section.css
- modules/features/cu_block_section/scss/cu-block-section.scss
To test:
1. Add Section Page Bundle
2. Create a block section with the default padding values
3. Create a section page and add/reference the block section created in step 2
4. Repeat step 3 (same block sections can be used) except hide page title
5. Repeat step 3 (same block sections can be used) except display section navigation
> Section Page padding Bug/150

- tests/behat/behat.travis.yml
> Hard coding version of chrome to use with js tests

- modules/custom/cu_mega_menu_bundle/cu_mega_menu/cu_mega_menu.install
- modules/custom/cu_mega_menu_bundle/cu_mega_menu/cu_mega_menu.module
If you're testing this on a site where this is already installed you'll need to run update.php
> adding descriptions for labels and headings #196

- themes/ucb/css/elements/forms.css
- themes/ucb/scss/elements/forms.scss
This PR does not change anything in how Express works or looks, only adds an export of the forms scss to a standalone css file.
> exporting form css partial #249

- express.info
- modules/custom/cu_core/cu_core.install
- modules/custom/cu_core/cu_core.module
- modules/custom/cu_help/cu_help.module
A fresh install or updated site should not display any of the additional help links.
> Disabling Express Help Module Bug/324

- modules/custom/cu_users/cu_users.install
- modules/custom/cu_users/cu_users.module
Remove developer role; keep content.
> remove developer role from user chmo0919

- modules/custom/cu_publications_bundle/cu_publication/Gemfile
- modules/custom/cu_publications_bundle/cu_publication/Gemfile.lock
- modules/custom/cu_publications_bundle/cu_publication/config.rb
- modules/custom/cu_publications_bundle/cu_publication/css/cu-publication.css
- modules/custom/cu_publications_bundle/cu_publication/scss/cu-publication.scss
- modules/custom/cu_shortcodes/Gemfile
- modules/custom/cu_shortcodes/Gemfile.lock
- modules/features/cu_article/Gemfile
- modules/features/cu_article/Gemfile.lock
- modules/features/cu_block_section/Gemfile
- modules/features/cu_block_section/Gemfile.lock
- modules/features/cu_feature_callout/Gemfile
- modules/features/cu_feature_callout/Gemfile.lock
- modules/features/cu_hero_unit/Gemfile
- modules/features/cu_hero_unit/Gemfile.lock
- modules/features/cu_social_links/Gemfile
- modules/features/cu_social_links/Gemfile.lock
- modules/features/people_content_type/Gemfile
- modules/features/people_content_type/Gemfile.lock
- themes/cuivory/Gemfile
- themes/cuivory/Gemfile.lock
- themes/ucb/Gemfile.lock
While working on this I also discovered some styles in cu_publication that required some gems that are no longer being used elsewhere and replaced that code with flexbox markup instead.
To test this, install the cu_publication bundle, created some issues with issue thumbnails, and go to issue/archive.
> Gemfile update Feature/326

- .github/workflows/action-update-express-upstream/entrypoint.sh
- .github/workflows/update-pantheon-upstream.yml
Updated path to workflow according to: https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions#jobsjob_idstepsuses
> Updated path to action-update-express-upstream in .yml file

- modules/custom/cu_livechat_bundle/cu_livechat_bundle.info
> chg: update livechat informational link !minor

- modules/custom/express_localist_bundle/express_localist_bundle.install
> Adding fac staff calendar filter to available filters.

- modules/custom/cu_users/cu_users.install
- modules/custom/cu_users/cu_users.module
> chg: add Alan Cole and Brooke Stevens to CU Users

- modules/custom/cu_core/cu_core.install
> Feature/120: Set Drupal Status Error for Mixed Mode or Secure Perms unlocked

- modules/features/cu_article/cu_article.module
This reverts commit 65583ef4661549967f761b9c043486b73ee761aa, reversing
changes made to b8266b2e3a27ab3b290b94ce503f60f8abfbe2c3.
> Revert "Merge pull request #504 from CuBoulder/bug/496"

- modules/custom/cu_block_to_bean/cu_block_to_bean.install
- modules/features/cu_search/css/cu-search.css
- modules/features/cu_search/cu_search.module
- modules/features/cu_search/scss/cu-search.scss
- modules/features/cu_search/templates/block--cu-search--cu-search-large.tpl.php
This block can be placed on a page with either context, or using the layout tool with the block wrapper.
> Add new block for large site search form

- modules/contrib/simplesamlphp_auth/simplesamlphp_auth-2476707-12.patch
- modules/contrib/simplesamlphp_auth/simplesamlphp_auth.pages.inc
Patch needed for SSO to redirect properly on Pantheon
> Applying simplesamlphp_auth-2476707-12.patch

- modules/contrib/simplesamlphp_auth/pantheon-sso-dashboard-redirect.patch
- modules/contrib/simplesamlphp_auth/simplesamlphp_auth.pages.inc
Upon successfully authenticating using SSO the user should be redirected to `/admin/dashboard`
> Bug/534 Patch for simplesamlphp_auth

- modules/custom/express_content_edit_lock/express_content_edit_lock.module
> Feature/420 c Update express_content_edit_lock module to work on Pantheon

- modules/custom/express_settings/express_settings.module
The title pretty much sums it up. I am not sure how or if it is possible to test this pr as I do not believe the code I deleted was being used.
> removed unused function with its broken link. Resolves #581

- modules/custom/cu_core/cu_core.info
> Add masquerade module to cu-core dependencies

- modules/contrib/elysia_cron/elysia_cron.drush.inc
- modules/contrib/elysia_cron/elysia_cron.info
- modules/contrib/elysia_cron/elysia_cron.module
elysia_cron module now is `7.x-2.8`
> Resolves #649

- modules/contrib/smart_trim/CHANGELOG.txt
- modules/contrib/smart_trim/README.txt
- modules/contrib/smart_trim/smart_trim.info
- modules/contrib/smart_trim/smart_trim.module
> resolves issue #658

- modules/custom/cu_core/cu_core.install
> chg: add missing quotes to array key !minor

- CHANGELOG.rst
- modules/custom/cu_core/cu_core.info
- modules/features/people_content_type/people_content_type_taxonomy.inc
Fix for an incorrect function call. To test be sure the news/article bundle is disabled.
> Hotfix: replacing incorrect function call. Resolves #736

- modules/custom/cu_js_includes/README.md
Includes steps for adding a JavaScript Include.
> New: Added README.md file.

- modules/custom/cu_js_includes/includes/cu_js_includes.types.inc
Simply changing misspellings found on LL 54-59 of `cu_js_includes/includes/cu_js_includes.types.inc`
> fix: correcting misspelling. Resolves #768

- modules/custom/cu_advanced_layout_bundle/cu_advanced_layout_bundle.info
- modules/custom/cu_advanced_layout_bundle/cu_advanced_layout_bundle.install
> Enable Javascript includes withe the Advanced Layout Bundle

- modules/custom/cu_js_includes/cu_js_includes.install
added update to Secure Perms module
closes #787
> chg: update secure perms for JS Includes

- modules/features/people_content_type/css/people_content_type.css
- modules/features/people_content_type/scss/people_content_type.scss
Changed selector used in people_content_type.scss for person photos from  to  in order to make it more specific to the intended situation.
Also compiled the scss into css.
> Fix: Change css selector. Resolves #782

- modules/custom/cu_newsletter_bundle/cu_newsletter/cu_newsletter.module
Note: I'm using the word "current" rather than "latest" in the URL in order to use the same pattern as the Issue bundle, which maps '/issue/current' to the latest issue.
> chg: add url item for current issue of newsletter
